# global constants
REQUIRED_GALLERY_FOLDER_IMAGES = "images"
REQUIRED_GALLERY_FOLDER_SMALL = "small"
REQUIRED_GALLERY_FILE_GALLERY = "gallery.xml"
REQUIRED_GALLERY_ELEMENTS = {REQUIRED_GALLERY_FILE_GALLERY,
                             REQUIRED_GALLERY_FOLDER_IMAGES, REQUIRED_GALLERY_FOLDER_SMALL}

THUMBNAIL_SIZE = (200, 200)
GALLERY_XML_IMAGES_TAG = "images"
GALLERY_XML_IMAGES_FILENAMW_TAG = "filename"

THUMB_SHARPEN_FACTOR = 1.5
THUMB_QUALITY = 70